### PR TITLE
py file added

### PR DESCRIPTION
**Pull request by Rezayzdni**
hi , this is a pull request in order to add py file to the master branch.

### CODE REVIEW

**Review by alitourani — CHANGES_REQUESTED** [review]
You have not added your "vide" and "pdf" files. Please take a look at the merged branches.

**Comment by Rezayzdni** [comment]
got it .

**Comment by Rezayzdni** [comment]
my video file is too big and github has limitations for it .
what should i do?
thanks.

**Comment by alitourani** [comment]
> my video file is too big and github has limitations for it .
> what should i do?
> thanks.

You can upload your description video anywhere and add the link in README.md
Like this:
- https://github.com/alitourani/ci-class-9802/tree/master/9-car-price-prediction
- https://github.com/alitourani/ci-class-9802/tree/master/2-gender-detection

**Comment by Rezayzdni** [comment]
got it .
thanks a lot.

**Review by alitourani — APPROVED** [review]

**Pull request merged**
