### PR TITLE
Group13 files added

### PR DESCRIPTION
**Pull request by aidaazbz**

### CODE REVIEW

**Review by alitourani — CHANGES_REQUESTED** [review]
Please also add your .PDF file (and dataset if possible):
Sample: https://github.com/alitourani/ci-class-9802/tree/master/9-car-price-prediction

**Comment by aidaazbz** [comment]
The codes have comments

**Comment by aidaazbz** [comment]
> Please also add your .PDF file (and dataset if possible):
> Sample: https://github.com/alitourani/ci-class-9802/tree/master/9-car-price-prediction

The codes have comments

**Comment by alitourani** [comment]
> > Please also add your .PDF file (and dataset if possible):
> > Sample: https://github.com/alitourani/ci-class-9802/tree/master/9-car-price-prediction
> 
> The codes have comments

Ok, I will merge your request, but the presentation (PDF) and description video files are essential to get the completed score.
If you want to add them, please consider another Pull Req.

**Pull request merged**
